##################################################
#   _____              _                         #
#   |_   _| __ __ _ ___| |__   ___ __ _ _ __     #
#     | || '__/ _` / __| '_ \ / __/ _` | '_ \    #
#     | || | | (_| \__ \ | | | (_| (_| | | | |   #
#     |_||_|  \__,_|___/_| |_|\___\__,_|_| |_|   #
#                                                #
##################################################

Trashcan:
  Type: CAULDRON

Inventory:
  Enabled: true
  Title: '&9Trashcan'

DroppedItem:
  AboveCauldron: true
  InCauldron: true

DisabledWorlds:
- notrashcanworld
